---

- name: Copy iperf script
  template:
    src: iperf.sh
    dest: /tmp/iperf.sh

- name: Modify script permissions
  command: sudo chmod +x /tmp/iperf.sh

- name: Run iperf test
  shell: ./iperf.sh {{ test_count }} {{ item }} >> {{ ansible_hostname }}_to_{{ item }}.iperf.log
  args:
    chdir: /tmp
  with_items:
    - "{{ groups['iperf_servers'] }}"

